"""add models.Company.url

Revision ID: a48f23424d16
Revises: ce9da2e84f58
Create Date: 2018-07-28 11:25:37.984467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48f23424d16'
down_revision = 'ce9da2e84f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('url', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'url')
    # ### end Alembic commands ###
