"""user.addtime

Revision ID: ce9da2e84f58
Revises: bfd7a0115ef9
Create Date: 2018-07-26 22:44:55.485169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce9da2e84f58'
down_revision = 'bfd7a0115ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('company', sa.Column('field', sa.String(length=64), nullable=True))
    op.add_column('company', sa.Column('financing', sa.String(length=64), nullable=True))
    op.add_column('company', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('job', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('job', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('job', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('job', 'job_describe')
    op.add_column('jobwanted', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('jobwanted', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('personal', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('personal', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_user_addtime', table_name='user')
    op.drop_column('user', 'addtime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('addtime', mysql.DATETIME(), nullable=True))
    op.create_index('ix_user_addtime', 'user', ['addtime'], unique=False)
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('personal', 'updated_at')
    op.drop_column('personal', 'created_at')
    op.drop_column('jobwanted', 'updated_at')
    op.drop_column('jobwanted', 'created_at')
    op.add_column('job', sa.Column('job_describe', mysql.TEXT(), nullable=True))
    op.drop_column('job', 'updated_at')
    op.drop_column('job', 'description')
    op.drop_column('job', 'created_at')
    op.drop_column('company', 'updated_at')
    op.drop_column('company', 'financing')
    op.drop_column('company', 'field')
    op.drop_column('company', 'created_at')
    # ### end Alembic commands ###
